/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppBrowseRouteImport } from './routes/app.browse'
import { Route as AppCalculatorRouteImport } from './routes/app.calculator'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppFavouritesRouteImport } from './routes/app.favourites'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as PoliciesIdRouteImport } from './routes/policies.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorRoute = AppCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFavouritesRoute = AppFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const PoliciesIdRoute = PoliciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PoliciesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/browse': typeof AppBrowseRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/favourites': typeof AppFavouritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/browse': typeof AppBrowseRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/favourites': typeof AppFavouritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/browse': typeof AppBrowseRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/favourites': typeof AppFavouritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/calculator'
    | '/contact'
    | '/login'
    | '/policies'
    | '/register'
    | '/app/applications'
    | '/app/assistant'
    | '/app/browse'
    | '/app/calculator'
    | '/app/dashboard'
    | '/app/favourites'
    | '/app/notifications'
    | '/app/profile'
    | '/policies/$id'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/contact'
    | '/login'
    | '/policies'
    | '/register'
    | '/app/applications'
    | '/app/assistant'
    | '/app/browse'
    | '/app/calculator'
    | '/app/dashboard'
    | '/app/favourites'
    | '/app/notifications'
    | '/app/profile'
    | '/policies/$id'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/calculator'
    | '/contact'
    | '/login'
    | '/policies'
    | '/register'
    | '/app/applications'
    | '/app/assistant'
    | '/app/browse'
    | '/app/calculator'
    | '/app/dashboard'
    | '/app/favourites'
    | '/app/notifications'
    | '/app/profile'
    | '/policies/$id'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PoliciesRoute: typeof PoliciesRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/browse': {
      id: '/app/browse'
      path: '/browse'
      fullPath: '/app/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculator': {
      id: '/app/calculator'
      path: '/calculator'
      fullPath: '/app/calculator'
      preLoaderRoute: typeof AppCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favourites': {
      id: '/app/favourites'
      path: '/favourites'
      fullPath: '/app/favourites'
      preLoaderRoute: typeof AppFavouritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/policies/$id': {
      id: '/policies/$id'
      path: '/$id'
      fullPath: '/policies/$id'
      preLoaderRoute: typeof PoliciesIdRouteImport
      parentRoute: typeof PoliciesRoute
    }
  }
}

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppBrowseRoute: typeof AppBrowseRoute
  AppCalculatorRoute: typeof AppCalculatorRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFavouritesRoute: typeof AppFavouritesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppBrowseRoute: AppBrowseRoute,
  AppCalculatorRoute: AppCalculatorRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFavouritesRoute: AppFavouritesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PoliciesRouteChildren {
  PoliciesIdRoute: typeof PoliciesIdRoute
}

const PoliciesRouteChildren: PoliciesRouteChildren = {
  PoliciesIdRoute: PoliciesIdRoute,
}

const PoliciesRouteWithChildren = PoliciesRoute._addFileChildren(
  PoliciesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PoliciesRoute: PoliciesRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
